# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bfe9da0acb8d0b0d4d006fae13a238617ab71d9384622f38684cbf1dd2421ba27ec5c9040849a6f6846ed57e28daf1ae16fae10a3ee7c23138c3558f2126bc5

test:
  secret_key_base: 735ddec5da85eb88a72630688ab31e6df4fa937fbe06fab2eb27b4a699d7bdc573eef81d2752228f415c696ad43d311044935981c3a1bb1002c6eddbc3a5e3c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
